data:
  probe_bag_dir: "ProbeBags/"
  robot_bag_dir: "SplitRoboBags/"
  window_length_seconds: 0.3
  window_stride_seconds: 0.2
  random_state: 42
  max_time_diff: 0.2  
  non_contact_threshold_factor: 0.1
  enable_squeezing: true
  dynamic_threshold_offset: 0.15

segmentation:
  amplitude_threshold: 0.05 
  cutoff_freq: 1000  
  squeeze_duration: 0.5  
  min_duration: 0.05  
  window_size_ms: 20  
  dynamic_threshold_percentile: 90

output:
  categories:
    - leaf
    - twig
    - trunk
    - ambient
  probe_dataset_dir: "audio_visual_dataset"
  robot_dataset_dir: "audio_visual_dataset_robo"

preprocessing:
  probe_noise_file: "humming.wav"
  robot_noise_file: "robo_humming.wav"
  noise_file: "humming.wav"
  enable_denoising: false
  do_norm: true
